branches:
  only:
    - master
language: node_js
node_js:
  - "node"
install:
  - npm i
script:
  - gulp compile
notifications:
  email:
    on_success: never
    on_failure: always
after_success: bash deploy.sh